### ISSUE TITLE
20220823 todo

### ISSUE THREAD

**Issue by SandwichBK** [SandwichDgk/SandwichDgk.github.io#1]
- [ ] 为《硕虎论氨》标题中加上”建洪志异“。
- [ ] 添加IFMOT tag，并加于《IFMO简介》。
- [ ] 删除”诗词“分类。
- [ ] 删除”不严谨诗文“tag，将其改为category，并将几篇诗文加入其中。
